apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-helm.fullname" . }}
  labels:
    {{- include "django-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "django-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "django-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or (.Values.imagePullSecrets.name) (.Values.imagePullSecrets.create) }}
      imagePullSecrets:
        - {{ include "django-helm.imagePullSecretsName" . }}
      {{- end }}
      serviceAccountName: {{ include "django-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- if .Values.deployment.command }}
          command: {{ .Values.deployment.command }}
          {{- end }}
          {{- with .Values.deployment.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}]
          {{- end }}
          envFrom:
            {{- if or (.Values.configMap.name) (.Values.configMap.create)  }}
            - configMapRef:
                name: {{- include "django-helm.configMapName" . }}
            {{- end }}
            {{- if or (.Values.secretConfig.name) (.Values.secretConfig.create) }}
            - secretRef:
                name: {{- include "django-helm.secretConfigName" . }}
            {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
