{{- if .Values.imagePullSecrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
  {{- with .Values.imagePullSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}

{{- end }}