{{- if .Values.imagePullSecrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-helm.imagePullSecretsName" . }}
  labels:
    {{- include "django-helm.labels" . | nindent 4 }}
  {{- with .Values.imagePullSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}

{{- end }}