{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- if .Values.imagePullSecrets.create }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecrets.name }}
{{- end }}

{{- end }}
