apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-helm.fullname" . }}
  labels:
    {{- include "django-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml  . | nindent 4}}
  {{- end }}
  selector:
    {{- include "django-helm.selectorLabels" . | nindent 4 }}
