{{- if .Values.secretConfig.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secretConfig.name }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
  {{- with .Values.secretConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.secretConfig.data }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- end }}